require("core.plugins.nvim-tree")
require("core.plugins.telescope")
require("core.plugins.theme")
require("core.plugins.lualine")
require("core.plugins.autopairs")
require("core.plugins.treesitter")
require("core.plugins.markdown-preview")
require("core.plugins.live-server")
-- lsp imports
require("core.plugins.lsp.mason")
require("core.plugins.lsp.nvim-cmp")
require("core.plugins.lsp.completion")
require("core.plugins.lsp.lspconfig")
require("core.plugins.lsp.lspsaga")
